name: Produce Acid
system:
  description:
    value: >-
      <p>A corrosive ball of acid appears hovering above your palm, and remains
      there for the duration. The acid produces no sound, and cannot harm you or
      your equipment. The Art ends if you dismiss it as an Action, or cast it
      again.</p><p>The acid can melt small and weak objects, such as thin chain
      links or textiles; doing so ends the Art.</p><p>You can also attack with
      the acid, although doing so ends the Art. When you cast this Art, or as an
      Action on a later Turn, you can hurl the acid at a Creature within 30 feet
      of you. Make a Ranged Spell Attack. On a hit, the target takes 1d8 Acid
      Damage.</p><p><strong>Cantrip Upgrade:</strong> The Damage increases by
      1d8 when you reach levels 5 (2d8), 11 (3d8), and 17
      (4d8).</p><p><strong>Automated.</strong></p>
    chat: ''
  source:
    custom: ''
    rules: '2014'
    revision: 1
    book: AK5e
    page: ''
    license: ''
  activation:
    type: bonus
    condition: ''
    value: null
  duration:
    value: '10'
    units: minute
  target:
    affects:
      choice: false
      count: ''
      type: self
      special: ''
    template:
      units: ft
      contiguous: false
      type: ''
  range:
    units: self
    special: ''
  uses:
    max: ''
    spent: 0
    recovery: []
  level: 0
  school: con
  properties:
    - somatic
  materials:
    value: ''
    consumed: false
    cost: 0
    supply: 0
  activities:
    MModRd17Oi6hhztj:
      type: utility
      name: Cast
      _id: MModRd17Oi6hhztj
      sort: 0
      activation:
        type: action
        value: null
        override: false
      consumption:
        scaling:
          allowed: false
        spellSlot: true
        targets: []
      description: {}
      duration:
        units: inst
        concentration: false
        override: false
      effects: []
      range:
        override: false
        units: self
      target:
        template:
          contiguous: false
          units: ft
        affects:
          choice: false
        override: false
        prompt: true
      uses:
        spent: 0
        recovery: []
      roll:
        prompt: false
        visible: false
      useConditionText: ''
      useConditionReason: ''
      effectConditionText: ''
      macroData:
        name: ''
        command: ''
      ignoreTraits:
        idi: false
        idr: false
        idv: false
        ida: false
        idm: false
      midiProperties:
        ignoreTraits: []
        triggeredActivityId: none
        triggeredActivityConditionText: ''
        triggeredActivityTargets: targets
        triggeredActivityRollAs: self
        autoConsume: false
        forceConsumeDialog: default
        forceRollDialog: default
        forceDamageDialog: default
        confirmTargets: default
        autoTargetType: any
        autoTargetAction: default
        automationOnly: false
        otherActivityCompatible: true
        otherActivityAsParentType: true
        identifier: ''
        displayActivityName: false
        rollMode: default
        chooseEffects: false
        toggleEffect: false
        ignoreFullCover: false
        removeChatButtons: default
        magicEffect: false
        magicDamage: false
        noConcentrationCheck: false
        autoCEEffects: default
      isOverTimeFlag: false
      overTimeProperties:
        saveRemoves: true
        preRemoveConditionText: ''
        postRemoveConditionText: ''
      otherActivityId: none
      otherActivityAsParentType: true
    tqKlIEdglRYdqHrp:
      type: attack
      name: Hurl Acid
      _id: tqKlIEdglRYdqHrp
      sort: 0
      activation:
        type: action
        value: null
        override: true
        condition: ''
      consumption:
        scaling:
          allowed: false
        spellSlot: true
        targets: []
      description:
        chatFlavor: ''
      duration:
        units: inst
        concentration: false
        override: true
      effects: []
      range:
        override: true
        units: ft
        special: ''
        value: '60'
      target:
        template:
          contiguous: false
          units: ft
          type: ''
        affects:
          choice: false
          count: '1'
          type: creatureOrObject
          special: ''
        override: true
        prompt: true
      uses:
        spent: 0
        recovery: []
        max: ''
      attack:
        critical:
          threshold: null
        flat: false
        type:
          value: ranged
          classification: ''
        ability: ''
        bonus: ''
      damage:
        critical:
          bonus: ''
        includeBase: true
        parts:
          - custom:
              enabled: false
              formula: ''
            number: 1
            denomination: 8
            bonus: ''
            types:
              - acid
            scaling:
              mode: whole
              number: 1
              formula: ''
      useConditionText: ''
      useConditionReason: ''
      effectConditionText: ''
      macroData:
        name: ''
        command: ''
      ignoreTraits:
        idi: false
        idr: false
        idv: false
        ida: false
        idm: false
      midiProperties:
        ignoreTraits: []
        triggeredActivityId: none
        triggeredActivityConditionText: ''
        triggeredActivityTargets: targets
        triggeredActivityRollAs: self
        autoConsume: false
        forceConsumeDialog: default
        forceRollDialog: default
        forceDamageDialog: default
        confirmTargets: default
        autoTargetType: any
        autoTargetAction: default
        automationOnly: false
        otherActivityCompatible: true
        otherActivityAsParentType: true
        identifier: ''
        displayActivityName: false
        rollMode: default
        chooseEffects: false
        toggleEffect: false
        ignoreFullCover: false
        removeChatButtons: default
        magicEffect: false
        magicDamage: true
        noConcentrationCheck: false
        autoCEEffects: default
      isOverTimeFlag: false
      overTimeProperties:
        saveRemoves: true
        preRemoveConditionText: ''
        postRemoveConditionText: ''
      otherActivityId: none
      otherActivityAsParentType: true
      attackMode: ''
      ammunition: ''
      otherActivityUuid: ''
      attackRollPerTarget: default
      fumbleThreshold: 1
  identifier: produce-acid
  method: spell
  prepared: 2
_id: L9KNkiqAh5KxKL90
type: spell
img: icons/magic/acid/dissolve-pool-bubbles.webp
effects: []
folder: yTaKQVDmOoYrR2OC
flags:
  dnd5e:
    riders:
      activity: []
      effect: []
_stats:
  compendiumSource: null
  duplicateSource: null
  exportSource: null
  coreVersion: '13.347'
  systemId: dnd5e
  systemVersion: 5.1.2
  createdTime: 1758563363515
  modifiedTime: 1758563363515
  lastModifiedBy: 9KtVYqHDTWORuJDZ
sort: 0
ownership:
  default: 0
  9KtVYqHDTWORuJDZ: 3
_key: '!items!L9KNkiqAh5KxKL90'
